"""
Regenerate app/questions.py with real-life scenarios and better hints.
Run: python update_questions.py
"""
import ast, copy, json

# Load existing questions
with open('app/questions.py', 'r') as f:
    content = f.read()
# Parse the QUESTIONS list
qs = eval(content.split('=', 1)[1].strip())

# Map of question id -> (new_description, new_hint)
updates = {
    1: ("Imagine you're building a calculator app. Before adding complex features, you need a simple function that always returns a fixed number.\n\nWrite a function `return_100` that simply returns the integer 100.\n\n🎯 Real-Life Use: Default values in apps, like a game starting score.\n\nExample Test Case:\nInput: `return_100()`\nExpected Output: `100`",
        "Just use the return keyword followed by the number 100."),
    2: ("You're building a Twitter-like app and need to count characters in a tweet to enforce the character limit.\n\nWrite a function `string_length(s)` that returns the length of string `s`.\n\n🎯 Real-Life Use: Character counters in messaging apps.\n\nExample Test Case:\nInput: `string_length('hello')`\nExpected Output: `5`",
        "Python has a built-in function called len() that counts characters."),
    3: ("A restaurant app doubles the quantity when a customer orders a 'Buy 1 Get 1' deal.\n\nWrite a function `multiply_by_two(n)` that returns `n` multiplied by 2.\n\n🎯 Real-Life Use: Doubling quantities in shopping carts.\n\nExample Test Case:\nInput: `multiply_by_two(4)`\nExpected Output: `8`",
        "Use the * operator to multiply n by 2."),
    4: ("In a music playlist, you want to quickly see what song plays first.\n\nReturn the first element of the list `lst`.\n\n🎯 Real-Life Use: Showing the next song in a queue.\n\nExample Test Case:\nInput: `first_element([10, 20, 30])`\nExpected Output: `10`",
        "Use index [0] to access the first item in a list."),
    5: ("In a chat app, you want to show the most recent message, which is the last one in the list.\n\nReturn the last element of the list `lst`.\n\n🎯 Real-Life Use: Showing the latest message in a conversation.\n\nExample Test Case:\nInput: `last_element([10, 20, 30])`\nExpected Output: `30`",
        "Use index [-1] to access the last item in a list."),
    6: ("Before displaying items in a shopping cart, you need to check if it's empty.\n\nReturn True if list is empty, else False.\n\n🎯 Real-Life Use: Showing 'Your cart is empty' messages.\n\nExample Test Case:\nInput: `is_empty([])`\nExpected Output: `True`",
        "An empty list is 'falsy' in Python. Try: return len(lst) == 0"),
    7: ("A greeting card app combines a user's first name and last name.\n\nReturn string `a` concatenated with `b`.\n\n🎯 Real-Life Use: Combining first and last names on profiles.\n\nExample Test Case:\nInput: `concat_strings('a', 'b')`\nExpected Output: `ab`",
        "Use the + operator to join two strings together."),
    8: ("You're calculating the area of a square room for a flooring app. Area = side × side.\n\nReturn the square of `n`.\n\n🎯 Real-Life Use: Area calculations in home design apps.\n\nExample Test Case:\nInput: `square(5)`\nExpected Output: `25`",
        "Use n * n or n ** 2 to square a number."),
    9: ("A banking app needs to check if an account balance is positive before allowing a withdrawal.\n\nReturn True if `n` is greater than 0, False otherwise.\n\n🎯 Real-Life Use: Balance checks before transactions.\n\nExample Test Case:\nInput: `is_positive(5)`\nExpected Output: `True`",
        "Use a comparison: return n > 0"),
    10: ("A weather app flags temperatures below zero to warn users about freezing conditions.\n\nReturn True if `n` is less than 0, False otherwise.\n\n🎯 Real-Life Use: Freeze warnings in weather apps.\n\nExample Test Case:\nInput: `is_negative(-5)`\nExpected Output: `True`",
        "Use a comparison: return n < 0"),
    11: ("A shopping app calculates the total when you buy two items.\n\nReturn sum of a and b.\n\n🎯 Real-Life Use: Adding prices in a cart.\n\nExample Test Case:\nInput: `sum_two(2, 3)`\nExpected Output: `5`",
        "Simply use the + operator: return a + b"),
    12: ("A GPS app calculates distance, which is always positive regardless of direction.\n\nReturn the absolute value of n.\n\n🎯 Real-Life Use: Distance is always positive.\n\nExample Test Case:\nInput: `abs_val(-5)`\nExpected Output: `5`",
        "Python has a built-in abs() function."),
    13: ("A contacts app filters names that start with 'A' for quick alphabetical lookup.\n\nReturn True if string starts with A or a.\n\n🎯 Real-Life Use: Filtering contacts by letter.\n\nExample Test Case:\nInput: `starts_with_a('Apple')`\nExpected Output: `True`",
        "Convert the first character to lowercase and compare: s[0].lower() == 'a'"),
    14: ("A spell checker flags words ending with 'z' as potentially unusual.\n\nReturn True if string ends with Z or z.\n\n🎯 Real-Life Use: Pattern matching in text editors.\n\nExample Test Case:\nInput: `ends_with_z('buzz')`\nExpected Output: `True`",
        "Check the last character: s[-1].lower() == 'z'"),
    15: ("An inventory system needs to quickly know how many products are in stock.\n\nReturn the number of elements in the list.\n\n🎯 Real-Life Use: Counting items in an inventory.\n\nExample Test Case:\nInput: `list_length([1,2,3])`\nExpected Output: `3`",
        "Use Python's built-in len() function."),
    16: ("A search feature checks if a specific product exists in the catalog.\n\nReturn True if x is in lst.\n\n🎯 Real-Life Use: Checking if an item is in stock.\n\nExample Test Case:\nInput: `contains_x([1,2,3], 2)`\nExpected Output: `True`",
        "Use Python's 'in' keyword: return x in lst"),
    17: ("A banner app repeats a pattern (like '⭐') multiple times for decoration.\n\nReturn string s repeated n times.\n\n🎯 Real-Life Use: Creating decorative text patterns.\n\nExample Test Case:\nInput: `repeat_string('hi', 3)`\nExpected Output: `hihihi`",
        "Use the * operator on strings: return s * n"),
    18: ("A settings app needs to list all available configuration options (dictionary keys).\n\nReturn a list of keys in dictionary d.\n\n🎯 Real-Life Use: Listing all settings in an app.\n\nExample Test Case:\nInput: `get_keys({'a':1})`\nExpected Output: `['a']`",
        "Use list(d.keys()) to get all keys as a list."),
    19: ("A gradebook app needs to extract just the scores (values) from a student's record.\n\nReturn a list of values in dictionary d.\n\n🎯 Real-Life Use: Extracting scores from a grade sheet.\n\nExample Test Case:\nInput: `get_values({'a':1})`\nExpected Output: `[1]`",
        "Use list(d.values()) to get all values as a list."),
    20: ("A seating app checks if a row number is even to assign aisle vs window seats.\n\nReturn True if n is even.\n\n🎯 Real-Life Use: Alternating row assignments.\n\nExample Test Case:\nInput: `is_even(4)`\nExpected Output: `True`",
        "A number is even if n % 2 == 0 (remainder is zero)."),
    21: ("A game assigns bonus points only on odd-numbered rounds.\n\nReturn True if n is odd.\n\n🎯 Real-Life Use: Round-based game logic.\n\nExample Test Case:\nInput: `is_odd(5)`\nExpected Output: `True`",
        "A number is odd if n % 2 != 0."),
    22: ("A ride-share app compares two route times and picks the faster one (larger speed = better).\n\nReturn the larger of a and b.\n\n🎯 Real-Life Use: Choosing the best option from two.\n\nExample Test Case:\nInput: `max_two(5, 10)`\nExpected Output: `10`",
        "Use Python's built-in max() function or an if statement."),
    23: ("A price comparison app finds the cheaper option between two stores.\n\nReturn the smaller of a and b.\n\n🎯 Real-Life Use: Finding the best deal.\n\nExample Test Case:\nInput: `min_two(5, 10)`\nExpected Output: `5`",
        "Use Python's built-in min() function or an if statement."),
    24: ("A chatbot greets every user by name when they log in.\n\nReturn 'Hello ' + name.\n\n🎯 Real-Life Use: Personalized greetings in apps.\n\nExample Test Case:\nInput: `hello_name('Bob')`\nExpected Output: `Hello Bob`",
        "Use string concatenation: 'Hello ' + name"),
    25: ("A username validator needs to check the first character of a username.\n\nReturn first character of s.\n\n🎯 Real-Life Use: Validating input fields.\n\nExample Test Case:\nInput: `first_char('cat')`\nExpected Output: `c`",
        "Access the first character with s[0]."),
    26: ("A file extension checker looks at the last character of a filename.\n\nReturn last character of s.\n\n🎯 Real-Life Use: Quick file type checks.\n\nExample Test Case:\nInput: `last_char('cat')`\nExpected Output: `t`",
        "Access the last character with s[-1]."),
    27: ("An alert system displays emergency messages in ALL CAPS for visibility.\n\nConvert string to uppercase.\n\n🎯 Real-Life Use: Emergency notifications.\n\nExample Test Case:\nInput: `to_upper('cat')`\nExpected Output: `CAT`",
        "Use the .upper() string method."),
    28: ("An email system normalizes addresses to lowercase for consistency.\n\nConvert string to lowercase.\n\n🎯 Real-Life Use: Email normalization.\n\nExample Test Case:\nInput: `to_lower('CAT')`\nExpected Output: `cat`",
        "Use the .lower() string method."),
    29: ("A form processor cleans up user input by removing accidental spaces.\n\nRemove leading and trailing spaces.\n\n🎯 Real-Life Use: Cleaning form inputs.\n\nExample Test Case:\nInput: `strip_spaces('  hi  ')`\nExpected Output: `hi`",
        "Use the .strip() string method."),
    30: ("A password strength checker counts how many times a specific character appears.\n\nCount how many times char appears in s.\n\n🎯 Real-Life Use: Password analysis.\n\nExample Test Case:\nInput: `count_occ('hello', 'l')`\nExpected Output: `2`",
        "Use the .count() string method."),
    31: ("A budget app adds up all your daily expenses to show the total.\n\nReturn sum of all numbers in list.\n\n🎯 Real-Life Use: Totaling expenses.\n\nExample Test Case:\nInput: `list_sum([1,2,3])`\nExpected Output: `6`",
        "Use Python's built-in sum() function."),
    32: ("A fitness app finds your highest score across all workouts.\n\nReturn largest number in list.\n\n🎯 Real-Life Use: Finding personal records.\n\nExample Test Case:\nInput: `list_max([1,5,2])`\nExpected Output: `5`",
        "Use Python's built-in max() function."),
    33: ("A weather app finds the coldest temperature of the week.\n\nReturn smallest number in list.\n\n🎯 Real-Life Use: Finding minimum temperature.\n\nExample Test Case:\nInput: `list_min([1,5,2])`\nExpected Output: `1`",
        "Use Python's built-in min() function."),
    34: ("A social media 'Stories' feature shows posts in reverse chronological order.\n\nReturn reversed list.\n\n🎯 Real-Life Use: Showing newest posts first.\n\nExample Test Case:\nInput: `reverse_list([1,2,3])`\nExpected Output: `[3, 2, 1]`",
        "Use slicing lst[::-1] or the list .reverse() method."),
    # Medium Questions
    35: ("An email list has duplicate addresses. Clean it up so each person gets only one email.\n\nReturn list with duplicates removed (order doesn't matter).\n\n🎯 Real-Life Use: Cleaning mailing lists.\n\nExample Test Case:\nInput: `sorted(remove_duplicates([1,2,2,3]))`\nExpected Output: `[1, 2, 3]`",
        "Convert the list to a set to remove duplicates, then back to a list."),
    36: ("A catering company calculates how many ways to arrange dishes. For 5 dishes: 5×4×3×2×1 = 120.\n\nReturn factorial of n (n >= 0).\n\n🎯 Real-Life Use: Calculating permutations for seating.\n\nExample Test Case:\nInput: `factorial(5)`\nExpected Output: `120`",
        "Use a loop multiplying from 1 to n, or use recursion. Remember 0! = 1."),
    37: ("A language learning app counts vowels in words to help with pronunciation practice.\n\nCount number of vowels (a,e,i,o,u) in string.\n\n🎯 Real-Life Use: Pronunciation analysis.\n\nExample Test Case:\nInput: `count_vowels('hello')`\nExpected Output: `2`",
        "Loop through each character and check if it's in 'aeiouAEIOU'."),
    38: ("A license plate reader checks if a code reads the same forwards and backwards (like 'RACECAR').\n\nReturn True if s reads the same forward and backward.\n\n🎯 Real-Life Use: Detecting palindromic codes.\n\nExample Test Case:\nInput: `is_palindrome('racecar')`\nExpected Output: `True`",
        "Compare the string to its reverse: s == s[::-1]"),
    39: ("Fibonacci numbers model rabbit population growth — each generation is the sum of the previous two.\n\nReturn nth Fibonacci number (0th is 0, 1st is 1).\n\n🎯 Real-Life Use: Population modeling, nature patterns.\n\nExample Test Case:\nInput: `fibonacci(5)`\nExpected Output: `5`",
        "Build up from fib(0)=0, fib(1)=1, each next = sum of previous two."),
    40: ("Two teams share player stats in separate dictionaries. Merge them into one master record.\n\nMerge two dictionaries, d2 overwrites d1 on conflict.\n\n🎯 Real-Life Use: Combining data from different sources.\n\nExample Test Case:\nInput: `merge_dicts({'a':1}, {'b':2})`\nExpected Output: `{'a': 1, 'b': 2}`",
        "Create a copy of d1 with {**d1, **d2} or use d1.copy() then .update(d2)."),
    41: ("A teacher's attendance sheet has roll numbers 0 to n, but one student is missing today.\n\nGiven list of numbers from 0 to n with one missing, find it.\n\n🎯 Real-Life Use: Finding missing attendance.\n\nExample Test Case:\nInput: `missing_number([0,1,3])`\nExpected Output: `2`",
        "The expected sum is n*(n+1)/2. Subtract the actual sum to find the missing number."),
    42: ("A bank's check reader adds up all digits in an account number for verification.\n\nReturn sum of digits of positive integer n.\n\n🎯 Real-Life Use: Check digit validation.\n\nExample Test Case:\nInput: `sum_digits(123)`\nExpected Output: `6`",
        "Convert n to string, loop through each character, convert back to int and sum."),
    43: ("A word game checks if two words use the exact same letters (like 'listen' and 'silent').\n\nReturn True if s1 and s2 are anagrams.\n\n🎯 Real-Life Use: Word puzzle games like Scrabble.\n\nExample Test Case:\nInput: `are_anagrams('listen', 'silent')`\nExpected Output: `True`",
        "Sort both strings and compare: sorted(s1) == sorted(s2)"),
    44: ("A teleprompter app reverses the word order so 'hello world' becomes 'world hello'.\n\nReverse the order of words in string.\n\n🎯 Real-Life Use: Text processing tools.\n\nExample Test Case:\nInput: `reverse_words('hello world')`\nExpected Output: `world hello`",
        "Split the string into words, reverse the list, then join back."),
    45: ("A reading level analyzer counts words in a sentence to estimate complexity.\n\nCount number of words in string separated by spaces.\n\n🎯 Real-Life Use: Readability scoring.\n\nExample Test Case:\nInput: `count_words('hello world')`\nExpected Output: `2`",
        "Split the string by spaces and count the resulting list length."),
    46: ("A keyboard app suggests the most-typed letter to optimize key placement.\n\nReturn the character that appears most often.\n\n🎯 Real-Life Use: Keyboard optimization.\n\nExample Test Case:\nInput: `most_frequent('hello')`\nExpected Output: `l`",
        "Use a dictionary to count occurrences, then find the max."),
    47: ("Two friend groups want to find people they have in common for a party invite.\n\nReturn common elements in both lists.\n\n🎯 Real-Life Use: Finding mutual friends.\n\nExample Test Case:\nInput: `sorted(intersection([1,2,3], [2,3,4]))`\nExpected Output: `[2, 3]`",
        "Convert both lists to sets and use the & operator or .intersection()."),
    48: ("A music app finds songs in your library that aren't in your friend's playlist.\n\nReturn elements in l1 not in l2.\n\n🎯 Real-Life Use: Finding unique songs.\n\nExample Test Case:\nInput: `sorted(difference([1,2,3], [2,3,4]))`\nExpected Output: `[1]`",
        "Convert to sets and use the - operator or .difference()."),
    49: ("An email app has folders within folders. Flatten them into one big list of all emails.\n\nFlatten a 2D list into a 1D list.\n\n🎯 Real-Life Use: Merging nested data.\n\nExample Test Case:\nInput: `flatten([[1,2], [3]])`\nExpected Output: `[1, 2, 3]`",
        "Use a list comprehension: [item for sublist in lst for item in sublist]"),
    50: ("A leaderboard sorts players by their scores, showing the lowest scorer first.\n\nReturn list of keys sorted by their ascending values.\n\n🎯 Real-Life Use: Ranking systems.\n\nExample Test Case:\nInput: `sort_dict({'a':3, 'b':1, 'c':2})`\nExpected Output: `['b', 'c', 'a']`",
        "Use sorted() with a key function: sorted(d, key=lambda k: d[k])"),
    51: ("A news app formats headlines in Title Case for a professional look.\n\nCapitalize first letter of every word.\n\n🎯 Real-Life Use: Formatting headlines.\n\nExample Test Case:\nInput: `title_case('hello world')`\nExpected Output: `Hello World`",
        "Use the .title() string method."),
    52: ("A computer science student is building a tool that converts binary code to regular numbers.\n\nConvert binary string to integer.\n\n🎯 Real-Life Use: Understanding how computers store data.\n\nExample Test Case:\nInput: `bin_to_dec('101')`\nExpected Output: `5`",
        "Use int(b, 2) to convert from binary string to decimal."),
    53: ("A math tutor app generates a list of prime numbers for practice problems.\n\nReturn list of prime numbers up to n.\n\n🎯 Real-Life Use: Educational math tools.\n\nExample Test Case:\nInput: `get_primes(10)`\nExpected Output: `[2, 3, 5, 7]`",
        "Check each number from 2 to n: a number is prime if no smaller number divides it evenly."),
    54: ("A recipe app scales ingredients. To simplify fractions like 12/8, you need their GCD (4), giving 3/2.\n\nReturn greatest common divisor of a and b.\n\n🎯 Real-Life Use: Simplifying fractions.\n\nExample Test Case:\nInput: `gcd(12, 8)`\nExpected Output: `4`",
        "Use the Euclidean algorithm: repeatedly do b, a%b until b is 0."),
    55: ("A scheduling app finds the earliest time two events can repeat together (like buses arriving every 4 and 6 minutes).\n\nReturn least common multiple of a and b.\n\n🎯 Real-Life Use: Scheduling synchronization.\n\nExample Test Case:\nInput: `lcm(4, 6)`\nExpected Output: `12`",
        "LCM = (a * b) // GCD(a, b). Calculate GCD first."),
    56: ("A spreadsheet app swaps rows and columns in a data table.\n\nReturn transposed 2D list.\n\n🎯 Real-Life Use: Pivoting data in spreadsheets.\n\nExample Test Case:\nInput: `transpose([[1,2], [3,4]])`\nExpected Output: `[[1, 3], [2, 4]]`",
        "Use zip(*matrix) and convert each tuple to a list."),
    57: ("A competition app needs to find the runner-up (2nd place) score.\n\nFind second largest number in list.\n\n🎯 Real-Life Use: Determining runner-up in competitions.\n\nExample Test Case:\nInput: `second_largest([1, 5, 3, 4])`\nExpected Output: `4`",
        "Sort the unique values and pick the second from the end."),
    58: ("A text filter removes vowels from words to create fun abbreviations (like 'hll' from 'hello').\n\nReturn string without vowels.\n\n🎯 Real-Life Use: Text abbreviation generators.\n\nExample Test Case:\nInput: `remove_vowels('hello')`\nExpected Output: `hll`",
        "Loop through characters and keep only non-vowels."),
    59: ("A database maps column names to their values — built from two parallel lists.\n\nCreate dict from list of keys and values.\n\n🎯 Real-Life Use: Building records from CSV headers and rows.\n\nExample Test Case:\nInput: `to_dict(['a','b'], [1,2])`\nExpected Output: `{'a': 1, 'b': 2}`",
        "Use dict(zip(keys, values))."),
    60: ("A cashier needs to find two items in a price list that add up to a customer's exact budget.\n\nFind two numbers in list that add up to target, return as sorted tuple. Return None if none.\n\n🎯 Real-Life Use: Budget matching.\n\nExample Test Case:\nInput: `find_pairs([1,2,3,4], 5)`\nExpected Output: `(1, 4)`",
        "Use a set to track seen numbers. For each num, check if target-num exists."),
    61: ("A delivery app verifies that package weights are arranged from lightest to heaviest.\n\nReturn True if list is sorted in ascending order.\n\n🎯 Real-Life Use: Verifying sorted data.\n\nExample Test Case:\nInput: `is_sorted([1,2,3])`\nExpected Output: `True`",
        "Compare the list to sorted(lst), or check each pair of adjacent elements."),
    62: ("A carousel display rotates images so the last few move to the front.\n\nRotate list to the right by k steps.\n\n🎯 Real-Life Use: Image carousel rotation.\n\nExample Test Case:\nInput: `rotate([1,2,3,4,5], 2)`\nExpected Output: `[4, 5, 1, 2, 3]`",
        "Use slicing: lst[-k:] + lst[:-k]. Handle k > len with k % len."),
    63: ("A DNA sequencer checks if a short pattern appears (in order) within a longer DNA strand.\n\nReturn True if s1 is a subsequence of s2.\n\n🎯 Real-Life Use: DNA sequence matching.\n\nExample Test Case:\nInput: `is_subsequence('abc', 'ahbgdc')`\nExpected Output: `True`",
        "Use two pointers — one for each string. Move through s2 and advance s1's pointer on match."),
    64: ("A fancy text generator alternates between uppercase and lowercase for stylish social media posts.\n\nCapitalize alternate letters.\n\n🎯 Real-Life Use: Aesthetic text generators.\n\nExample Test Case:\nInput: `alt_caps('hello')`\nExpected Output: `HeLlO`",
        "Loop with enumerate. Even index = upper, odd index = lower."),
    65: ("A networking tool counts the number of '1' bits in a binary IP address.\n\nReturn number of 1s in binary representation of n.\n\n🎯 Real-Life Use: Network subnet calculations.\n\nExample Test Case:\nInput: `count_bits(5)`\nExpected Output: `2`",
        "Convert to binary string with bin(n) and count '1' characters."),
    66: ("A memory manager checks if a block size is a power of 2 for optimal allocation.\n\nReturn True if n is power of two.\n\n🎯 Real-Life Use: Memory allocation optimization.\n\nExample Test Case:\nInput: `is_power_of_two(8)`\nExpected Output: `True`",
        "A power of 2 has exactly one '1' bit: n > 0 and n & (n-1) == 0."),
    67: ("A dictionary app groups words that are anagrams of each other. Just count how many groups there are.\n\nGroup anagrams together and return the count of groups.\n\n🎯 Real-Life Use: Word game scoring.\n\nExample Test Case:\nInput: `group_anagrams_medium(['eat', 'tea', 'tan'])`\nExpected Output: `2`",
        "Sort each word's letters as a key, group by that key, count groups."),
    # Hard Questions
    68: ("A text editor's 'Find' feature highlights the longest palindromic word or phrase in your document.\n\nReturn the longest palindromic substring.\n\n🎯 Real-Life Use: Text pattern analysis.\n\nExample Test Case:\nInput: `longest_palindrome('babad') in ['bab', 'aba']`\nExpected Output: `True`",
        "Expand around each center (character and between characters) to find palindromes."),
    69: ("A calendar app merges overlapping meetings so your schedule looks clean.\n\nMerge overlapping intervals.\n\n🎯 Real-Life Use: Calendar conflict resolution.\n\nExample Test Case:\nInput: `merge_intervals([[1,3],[2,6],[8,10]])`\nExpected Output: `[[1, 6], [8, 10]]`",
        "Sort by start time, then merge if current interval overlaps with the last merged one."),
    70: ("After rain, water collects between buildings of different heights. Calculate total trapped water.\n\nCalculate how much water can be trapped after raining.\n\n🎯 Real-Life Use: Civil engineering drainage planning.\n\nExample Test Case:\nInput: `trap([0,1,0,2,1,0,1,3,2,1,2,1])`\nExpected Output: `6`",
        "For each position, water = min(max_left, max_right) - height. Pre-compute max arrays."),
    71: ("An autocomplete system checks if a typed string can be broken into valid dictionary words.\n\nReturn True if string can be segmented into dictionary words.\n\n🎯 Real-Life Use: Spell checkers and autocomplete.\n\nExample Test Case:\nInput: `word_break('leetcode', ['leet', 'code'])`\nExpected Output: `True`",
        "Use dynamic programming: dp[i] = True if s[:i] can be segmented."),
    72: ("A historian discovers scattered years in records and wants the longest streak of consecutive years.\n\nFind length of longest consecutive elements sequence.\n\n🎯 Real-Life Use: Finding patterns in historical data.\n\nExample Test Case:\nInput: `longest_consecutive([100, 4, 200, 1, 3, 2])`\nExpected Output: `4`",
        "Use a set. For each number that's a sequence start (n-1 not in set), count the streak."),
    73: ("An autocorrect feature calculates the minimum edits (insert, delete, replace) to fix a typo.\n\nMinimum operations to convert word1 to word2.\n\n🎯 Real-Life Use: Spell check suggestions.\n\nExample Test Case:\nInput: `edit_distance('horse', 'ros')`\nExpected Output: `3`",
        "Use a 2D DP table. Compare characters and take min of insert, delete, replace."),
    74: ("A stock trader wants to find the best consecutive days of profit to maximize returns.\n\nReturn max sum of contiguous subarray.\n\n🎯 Real-Life Use: Stock market analysis.\n\nExample Test Case:\nInput: `max_subarray([-2,1,-3,4,-1,2,1,-5,4])`\nExpected Output: `6`",
        "Use Kadane's algorithm: track current sum and max sum. Reset current if it goes negative."),
    75: ("A vending machine needs to give change using the fewest coins possible.\n\nMinimum coins to make amount.\n\n🎯 Real-Life Use: Optimal change-making.\n\nExample Test Case:\nInput: `coin_change([1,2,5], 11)`\nExpected Output: `3`",
        "Use DP: dp[i] = min coins for amount i. Try each coin denomination."),
    76: ("A puzzle game validates if a partially filled Sudoku board follows the rules.\n\nValidate a partially filled 9x9 sudoku board.\n\n🎯 Real-Life Use: Sudoku game validation.\n\nExample Test Case:\nInput: `is_valid_sudoku([['5','3','.','.','7','.','.','.','.'],['6','.','.','1','9','5','.','.','.'],['.','9','8','.','.','.','.','6','.'],['8','.','.','.','6','.','.','.','3'],['4','.','.','8','.','3','.','.','1'],['7','.','.','.','2','.','.','.','6'],['.','6','.','.','.','.','2','8','.'],['.','.','.','4','1','9','.','.','5'],['.','.','.','.','8','.','.','7','9']])`\nExpected Output: `True`",
        "Check each row, column, and 3x3 box for duplicate non-dot values using sets."),
    77: ("A math tool generates all valid combinations of balanced parentheses for teaching.\n\nReturn list of all well-formed parentheses strings.\n\n🎯 Real-Life Use: Teaching combinatorics.\n\nExample Test Case:\nInput: `sorted(generate_parentheses(3))`\nExpected Output: `['((()))', '(()())', '(())()', '()(())', '()()()']`",
        "Use recursion/backtracking: add '(' if open < n, add ')' if close < open."),
    78: ("A travel planner finds every possible order to visit a set of cities.\n\nReturn all possible permutations of list.\n\n🎯 Real-Life Use: Route planning.\n\nExample Test Case:\nInput: `sorted(permute([1,2]))`\nExpected Output: `[[1, 2], [2, 1]]`",
        "Use recursion: fix one element, permute the rest. Or use itertools.permutations."),
    79: ("A meal planner generates every possible combination of dishes from a menu.\n\nReturn all possible subsets.\n\n🎯 Real-Life Use: Combination generators.\n\nExample Test Case:\nInput: `sorted(subsets([1,2]))`\nExpected Output: `[[], [1], [1, 2], [2]]`",
        "Use backtracking or iterative approach: for each element, add it to all existing subsets."),
    80: ("A frog wants to reach the end of a pond by jumping on lily pads. Each pad tells max jump distance.\n\nDetermine if you can reach the last index.\n\n🎯 Real-Life Use: Game level reachability.\n\nExample Test Case:\nInput: `can_jump([2,3,1,1,4])`\nExpected Output: `True`",
        "Track the farthest reachable index. If current > farthest, return False."),
    81: ("A delivery robot can only move right or down in a grid. Count all possible routes.\n\nFind number of unique paths in m x n grid.\n\n🎯 Real-Life Use: Robot path planning.\n\nExample Test Case:\nInput: `unique_paths(3, 7)`\nExpected Output: `28`",
        "Use DP: dp[i][j] = dp[i-1][j] + dp[i][j-1]. First row and column are all 1s."),
    82: ("You're climbing a staircase and can take 1 or 2 steps at a time. How many distinct ways to reach the top?\n\nDistinct ways to climb n stairs (1 or 2 steps).\n\n🎯 Real-Life Use: Counting possibilities in step-based games.\n\nExample Test Case:\nInput: `climb_stairs(3)`\nExpected Output: `3`",
        "This is the Fibonacci pattern! ways(n) = ways(n-1) + ways(n-2)."),
    83: ("A sorted phone book got shuffled (rotated). Find a specific contact quickly.\n\nReturn index of target in rotated sorted array, or -1.\n\n🎯 Real-Life Use: Searching in rotated datasets.\n\nExample Test Case:\nInput: `search([4,5,6,7,0,1,2], 0)`\nExpected Output: `4`",
        "Use modified binary search: determine which half is sorted, then decide which half to search."),
    84: ("A data logger converts a list of sensor readings into a formatted string.\n\nSimply return string representation.\n\n🎯 Real-Life Use: Data formatting for display.\n\nExample Test Case:\nInput: `tree_to_str([1,2,3])`\nExpected Output: `[1, 2, 3]`",
        "Use str() to convert the list to its string representation."),
    85: ("A hiking app finds the highest point (peak) along a trail profile.\n\nReturn index of peak element.\n\n🎯 Real-Life Use: Finding mountain peaks in elevation data.\n\nExample Test Case:\nInput: `find_peak([1,2,3,1])`\nExpected Output: `2`",
        "Use binary search: if mid < mid+1, peak is to the right; otherwise to the left."),
    86: ("A code validator checks the longest stretch of properly matched brackets in source code.\n\nLength of longest valid parentheses substring.\n\n🎯 Real-Life Use: Code syntax validation.\n\nExample Test Case:\nInput: `longest_valid(')()())')`\nExpected Output: `4`",
        "Use a stack to track indices of unmatched parentheses."),
    87: ("A GPS finds the path through a city grid (top-left to bottom-right) that minimizes total toll costs.\n\nFind path from top left to bottom right minimizing sum.\n\n🎯 Real-Life Use: Optimal route with tolls.\n\nExample Test Case:\nInput: `min_path_sum([[1,3,1],[1,5,1],[4,2,1]])`\nExpected Output: `7`",
        "Use DP: dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1])."),
    88: ("A spy decoder figures out how many ways a numeric code can be translated to letters (1=A, 2=B, ..., 26=Z).\n\nNumber of ways to decode digit string.\n\n🎯 Real-Life Use: Cryptographic decoding.\n\nExample Test Case:\nInput: `num_decodings('226')`\nExpected Output: `3`",
        "Use DP: single digit (1-9) and double digit (10-26) contribute to count."),
    89: ("A file search tool uses wildcards: '?' matches any single character, '*' matches any sequence.\n\nImplement wildcard matching with ? and *.\n\n🎯 Real-Life Use: File search patterns (*.txt, photo_?.jpg).\n\nExample Test Case:\nInput: `is_match('aa', '*')`\nExpected Output: `True`",
        "Use DP: dp[i][j] = does s[:i] match p[:j]. Handle '*' specially."),
    90: ("A chess tournament organizer needs to place N queens on an N×N board so none attack each other.\n\nReturn number of distinct solutions to N-Queens puzzle.\n\n🎯 Real-Life Use: Constraint satisfaction problems.\n\nExample Test Case:\nInput: `total_n_queens(4)`\nExpected Output: `2`",
        "Use backtracking: place queens row by row, checking column and diagonal conflicts."),
    91: ("An architect finds the largest rectangular room that fits in an irregular building floor plan.\n\nFind largest rectangle of 1s in 2D binary matrix.\n\n🎯 Real-Life Use: Maximizing usable space.\n\nExample Test Case:\nInput: `maximal_rectangle([['1','0','1','0','0'],['1','0','1','1','1'],['1','1','1','1','1'],['1','0','0','1','0']])`\nExpected Output: `6`",
        "Build histogram heights per row, then use largest rectangle in histogram algorithm."),
    92: ("A playlist mixer checks if a combined playlist could have been made by interleaving two original playlists in order.\n\nDetermine if s3 is an interleaving of s1 and s2.\n\n🎯 Real-Life Use: Merge verification.\n\nExample Test Case:\nInput: `is_interleave('aabcc', 'dbbca', 'aadbbcbcac')`\nExpected Output: `True`",
        "Use 2D DP: dp[i][j] = can s1[:i] and s2[:j] form s3[:i+j]."),
    93: ("A genetics lab counts how many ways a short DNA pattern appears as a subsequence in a longer strand.\n\nNumber of distinct subsequences of s that equal t.\n\n🎯 Real-Life Use: Gene pattern counting.\n\nExample Test Case:\nInput: `num_distinct('rabbbit', 'rabbit')`\nExpected Output: `3`",
        "Use 2D DP: dp[i][j] = number of ways to form t[:j] from s[:i]."),
    94: ("A network router finds the shortest chain of one-letter-changes to transform one word into another.\n\nShortest transformation sequence from begin to end word.\n\n🎯 Real-Life Use: Network routing algorithms.\n\nExample Test Case:\nInput: `ladder_length('hit', 'cog', ['hot','dot','dog','lot','log','cog'])`\nExpected Output: `5`",
        "Use BFS: each level changes one letter. Try all 26 letters at each position."),
    95: ("A sports app quickly finds the silver medalist (2nd highest) score from a list of results.\n\nFind kth largest element.\n\n🎯 Real-Life Use: Ranking athletes.\n\nExample Test Case:\nInput: `find_kth_largest([3,2,1,5,6,4], 2)`\nExpected Output: `5`",
        "Sort and pick, or use a heap for efficiency: sorted(nums)[-k]"),
    96: ("An election system finds which candidate got more than half the total votes.\n\nFind majority element.\n\n🎯 Real-Life Use: Election result analysis.\n\nExample Test Case:\nInput: `majority_element([3,2,3])`\nExpected Output: `3`",
        "Boyer-Moore voting: keep a candidate and count. Or just sort and pick the middle."),
    97: ("A library catalog is organized in a sorted 2D table. Find a specific book quickly.\n\nSearch for value in 2D sorted matrix.\n\n🎯 Real-Life Use: Efficient database lookups.\n\nExample Test Case:\nInput: `search_matrix([[1,3,5,7],[10,11,16,20],[23,30,34,60]], 3)`\nExpected Output: `True`",
        "Treat the 2D matrix as a 1D sorted array and use binary search."),
    98: ("A photo editor rotates an image 90 degrees clockwise.\n\nRotate nxn matrix 90 degrees clockwise in-place, then return it.\n\n🎯 Real-Life Use: Image rotation in editors.\n\nExample Test Case:\nInput: `rotate_image([[1,2,3],[4,5,6],[7,8,9]])`\nExpected Output: `[[7, 4, 1], [8, 5, 2], [9, 6, 3]]`",
        "Transpose the matrix, then reverse each row."),
    99: ("A dictionary app groups words that are anagrams (same letters, different order) together.\n\nGroup anagrams together and return list of lists.\n\n🎯 Real-Life Use: Word game helpers.\n\nExample Test Case:\nInput: `sorted([sorted(x) for x in group_anagrams(['eat','tea','tan','ate','nat','bat'])])`\nExpected Output: `[['ate', 'eat', 'tea'], ['bat'], ['nat', 'tan']]`",
        "Use a dict with sorted word as key, group words under each key."),
    100: ("A word game checks if one word can be rearranged to form another (like 'anagram' → 'nagaram').\n\nReturn True if t is an anagram of s.\n\n🎯 Real-Life Use: Word game validation.\n\nExample Test Case:\nInput: `is_anagram('anagram', 'nagaram')`\nExpected Output: `True`",
        "Sort both and compare, or use a character frequency counter."),
}

# Apply updates
for q in qs:
    qid = q['id']
    if qid in updates:
        q['description'] = updates[qid][0]
        q['hint'] = updates[qid][1]

# Write out
import pprint
with open('app/questions.py', 'w', encoding='utf-8') as f:
    f.write('QUESTIONS = ')
    pp = pprint.PrettyPrinter(indent=2, width=120, stream=f)
    pp.pprint(qs)
    f.write('\n')

print(f"✅ Updated {len(updates)} questions with real-life scenarios!")
