QUESTIONS = [
    {
        "id": 1, "difficulty": "Easy", "points": 100,
        "title": "Hello World",
        "description": "Write a function `hello_world` that returns the string 'Hello World!'.\n\nExample:\n  hello_world() → 'Hello World!'",
        "starter": "def hello_world():\n    # your code here\n    pass",
        "tests": [
            {"input": "hello_world()", "expected": "Hello World!"},
        ],
        "hint": "Use the return keyword followed by the string.",
        "tags": ["basics", "strings"],
    },
    {
        "id": 2, "difficulty": "Easy", "points": 100,
        "title": "Add Two Numbers",
        "description": "Write a function `add(a, b)` that takes two numbers and returns their sum.\n\nExample:\n  add(2, 3) → 5",
        "starter": "def add(a, b):\n    # your code here\n    pass",
        "tests": [
            {"input": "add(2, 3)", "expected": 5},
            {"input": "add(-1, 5)", "expected": 4},
            {"input": "add(0, 0)", "expected": 0},
        ],
        "hint": "Use the + operator.",
        "tags": ["basics", "math"],
    },
    {
        "id": 3, "difficulty": "Easy", "points": 100,
        "title": "Even or Odd",
        "description": "Write a function `is_even(n)` that returns True if the given integer n is even, and False otherwise.\n\nExample:\n  is_even(4) → True\n  is_even(7) → False",
        "starter": "def is_even(n):\n    # your code here\n    pass",
        "tests": [
            {"input": "is_even(4)", "expected": True},
            {"input": "is_even(7)", "expected": False},
            {"input": "is_even(0)", "expected": True},
        ],
        "hint": "Use the modulo operator % to check if the remainder when dividing by 2 is 0.",
        "tags": ["math", "conditionals"],
    },
    {
        "id": 4, "difficulty": "Easy", "points": 100,
        "title": "Max of Two Numbers",
        "description": "Write a function `max_num(a, b)` that returns the larger of the two numbers.\n\nExample:\n  max_num(10, 20) → 20\n  max_num(5, 5) → 5",
        "starter": "def max_num(a, b):\n    # your code here\n    pass",
        "tests": [
            {"input": "max_num(10, 20)", "expected": 20},
            {"input": "max_num(-5, 0)", "expected": 0},
            {"input": "max_num(5, 5)", "expected": 5},
        ],
        "hint": "You can use an if-else statement or the built-in max() function.",
        "tags": ["basics", "conditionals"],
    },
    {
        "id": 5, "difficulty": "Easy", "points": 100,
        "title": "Reverse a String",
        "description": "Write a function `reverse_string(s)` that takes a string and returns it reversed.\n\nExample:\n  reverse_string('hello') → 'olleh'",
        "starter": "def reverse_string(s):\n    # your code here\n    pass",
        "tests": [
            {"input": "reverse_string('hello')", "expected": "olleh"},
            {"input": "reverse_string('world')", "expected": "dlrow"},
            {"input": "reverse_string('a')", "expected": "a"},
            {"input": "reverse_string('')", "expected": ""},
        ],
        "hint": "You can use string slicing: s[::-1].",
        "tags": ["strings", "basics"],
    },
    {
        "id": 6, "difficulty": "Medium", "points": 150,
        "title": "Factorial",
        "description": "Write a function `factorial(n)` that returns the factorial of a non-negative integer n. The factorial of n is the product of all positive integers less than or equal to n. The factorial of 0 is 1.\n\nExample:\n  factorial(5) → 120",
        "starter": "def factorial(n):\n    # your code here\n    pass",
        "tests": [
            {"input": "factorial(5)", "expected": 120},
            {"input": "factorial(0)", "expected": 1},
            {"input": "factorial(1)", "expected": 1},
            {"input": "factorial(4)", "expected": 24},
        ],
        "hint": "Use a loop or recursion.",
        "tags": ["math", "recursion", "loops"],
    },
    {
        "id": 7, "difficulty": "Medium", "points": 150,
        "title": "Count Vowels",
        "description": "Write a function `count_vowels(s)` that counts the number of vowels (a, e, i, o, u) in a given string. Treat both uppercase and lowercase as vowels.\n\nExample:\n  count_vowels('hello') → 2\n  count_vowels('WORLD') → 1",
        "starter": "def count_vowels(s):\n    # your code here\n    pass",
        "tests": [
            {"input": "count_vowels('hello')", "expected": 2},
            {"input": "count_vowels('WORLD')", "expected": 1},
            {"input": "count_vowels('bcd')", "expected": 0},
            {"input": "count_vowels('AaEeIiOoUu')", "expected": 10},
        ],
        "hint": "Iterate through the string and check if each character is in 'aeiouAEIOU'.",
        "tags": ["strings", "loops"],
    },
    {
        "id": 8, "difficulty": "Medium", "points": 150,
        "title": "Check Palindrome",
        "description": "Write a function `is_palindrome(s)` that checks if a given string is a palindrome (reads the same forwards and backwards).\n\nExample:\n  is_palindrome('racecar') → True\n  is_palindrome('hello') → False",
        "starter": "def is_palindrome(s):\n    # your code here\n    pass",
        "tests": [
            {"input": "is_palindrome('racecar')", "expected": True},
            {"input": "is_palindrome('hello')", "expected": False},
            {"input": "is_palindrome('a')", "expected": True},
            {"input": "is_palindrome('abba')", "expected": True},
        ],
        "hint": "Compare the string with its reverse.",
        "tags": ["strings", "basics"],
    },
    {
        "id": 9, "difficulty": "Medium", "points": 150,
        "title": "List of Squares",
        "description": "Write a function `get_squares(n)` that returns a list of the squares of all numbers from 1 to n (inclusive).\n\nExample:\n  get_squares(4) → [1, 4, 9, 16]",
        "starter": "def get_squares(n):\n    # your code here\n    pass",
        "tests": [
            {"input": "get_squares(4)", "expected": [1, 4, 9, 16]},
            {"input": "get_squares(1)", "expected": [1]},
            {"input": "get_squares(0)", "expected": []},
        ],
        "hint": "Use a list comprehension or a loop with append().",
        "tags": ["lists", "loops"],
    },
    {
        "id": 10, "difficulty": "Medium", "points": 150,
        "title": "Find Largest in List",
        "description": "Write a function `find_largest(nums)` that takes a list of numbers and returns the largest number. If the list is empty, return None.\n\nExample:\n  find_largest([1, 5, 3, 9, 2]) → 9",
        "starter": "def find_largest(nums):\n    # your code here\n    pass",
        "tests": [
            {"input": "find_largest([1, 5, 3, 9, 2])", "expected": 9},
            {"input": "find_largest([-1, -5, -3])", "expected": -1},
            {"input": "find_largest([10])", "expected": 10},
            {"input": "find_largest([])", "expected": None},
        ],
        "hint": "You can use the built-in max() function or iterate to find the max.",
        "tags": ["lists", "basics"],
    }
]
