QUESTIONS = [{'id': 1,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Return 100',
  'description': 'Write a function `return_100` that simply returns the integer 100.',
  'starter': 'def return_100():\n    pass',
  'tests': [{'input': 'return_100()', 'expected': 100}],
  'hint': 'Try writing out standard python.',
  'tags': ['basics']},
 {'id': 2,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'String Length',
  'description': 'Write a function `string_length(s)` that returns the length of string `s`.',
  'starter': 'def string_length(s):\n    pass',
  'tests': [{'input': "string_length('hello')", 'expected': 5}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 3,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Multiply by 2',
  'description': 'Write a function `multiply_by_two(n)` that returns `n` multiplied by 2.',
  'starter': 'def multiply_by_two(n):\n    pass',
  'tests': [{'input': 'multiply_by_two(4)', 'expected': 8}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 4,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'First Element',
  'description': 'Return the first element of the list `lst`.',
  'starter': 'def first_element(lst):\n    pass',
  'tests': [{'input': 'first_element([10, 20, 30])', 'expected': 10}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists']},
 {'id': 5,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Last Element',
  'description': 'Return the last element of the list `lst`.',
  'starter': 'def last_element(lst):\n    pass',
  'tests': [{'input': 'last_element([10, 20, 30])', 'expected': 30}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists']},
 {'id': 6,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Is Empty',
  'description': 'Return True if list is empty, else False.',
  'starter': 'def is_empty(lst):\n    pass',
  'tests': [{'input': 'is_empty([])', 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists', 'conditionals']},
 {'id': 7,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Concat Strings',
  'description': 'Return string `a` concatenated with `b`.',
  'starter': 'def concat_strings(a, b):\n    pass',
  'tests': [{'input': "concat_strings('a', 'b')", 'expected': 'ab'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 8,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Square a Number',
  'description': 'Return the square of `n`.',
  'starter': 'def square(n):\n    pass',
  'tests': [{'input': 'square(5)', 'expected': 25}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 9,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Is Positive',
  'description': 'Return True if `n` is greater than 0, False otherwise.',
  'starter': 'def is_positive(n):\n    pass',
  'tests': [{'input': 'is_positive(5)', 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['math', 'conditionals']},
 {'id': 10,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Is Negative',
  'description': 'Return True if `n` is less than 0, False otherwise.',
  'starter': 'def is_negative(n):\n    pass',
  'tests': [{'input': 'is_negative(-5)', 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['math', 'conditionals']},
 {'id': 11,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Sum of Two',
  'description': 'Return sum of a and b.',
  'starter': 'def sum_two(a, b):\n    pass',
  'tests': [{'input': 'sum_two(2, 3)', 'expected': 5}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 12,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Absolute Value',
  'description': 'Return absolute value of n.',
  'starter': 'def abs_val(n):\n    pass',
  'tests': [{'input': 'abs_val(-5)', 'expected': 5}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 13,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Starts with A',
  'description': 'Return True if string starts with A or a.',
  'starter': 'def starts_with_a(s):\n    pass',
  'tests': [{'input': "starts_with_a('Apple')", 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 14,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Ends with Z',
  'description': 'Return True if string ends with Z or z.',
  'starter': 'def ends_with_z(s):\n    pass',
  'tests': [{'input': "ends_with_z('buzz')", 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 15,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'List Length',
  'description': 'Return the number of elements in the list.',
  'starter': 'def list_length(lst):\n    pass',
  'tests': [{'input': 'list_length([1,2,3])', 'expected': 3}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists']},
 {'id': 16,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Contains X',
  'description': 'Return True if x is in lst.',
  'starter': 'def contains_x(lst, x):\n    pass',
  'tests': [{'input': 'contains_x([1,2,3], 2)', 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists']},
 {'id': 17,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Repeat String',
  'description': 'Return string s repeated n times.',
  'starter': 'def repeat_string(s, n):\n    pass',
  'tests': [{'input': "repeat_string('hi', 3)", 'expected': 'hihihi'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 18,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Get Keys',
  'description': 'Return a list of keys in dictionary d.',
  'starter': 'def get_keys(d):\n    pass',
  'tests': [{'input': "get_keys({'a':1})", 'expected': ['a']}],
  'hint': 'Try writing out standard python.',
  'tags': ['dicts']},
 {'id': 19,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Get Values',
  'description': 'Return a list of values in dictionary d.',
  'starter': 'def get_values(d):\n    pass',
  'tests': [{'input': "get_values({'a':1})", 'expected': [1]}],
  'hint': 'Try writing out standard python.',
  'tags': ['dicts']},
 {'id': 20,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Check Even',
  'description': 'Return True if n is even.',
  'starter': 'def is_even(n):\n    pass',
  'tests': [{'input': 'is_even(4)', 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 21,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Check Odd',
  'description': 'Return True if n is odd.',
  'starter': 'def is_odd(n):\n    pass',
  'tests': [{'input': 'is_odd(5)', 'expected': True}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 22,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Max of Two',
  'description': 'Return the larger of a and b.',
  'starter': 'def max_two(a, b):\n    pass',
  'tests': [{'input': 'max_two(5, 10)', 'expected': 10}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 23,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Min of Two',
  'description': 'Return the smaller of a and b.',
  'starter': 'def min_two(a, b):\n    pass',
  'tests': [{'input': 'min_two(5, 10)', 'expected': 5}],
  'hint': 'Try writing out standard python.',
  'tags': ['math']},
 {'id': 24,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Hello Name',
  'description': "Return 'Hello ' + name.",
  'starter': 'def hello_name(name):\n    pass',
  'tests': [{'input': "hello_name('Bob')", 'expected': 'Hello Bob'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 25,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'First Char',
  'description': 'Return first character of s.',
  'starter': 'def first_char(s):\n    pass',
  'tests': [{'input': "first_char('cat')", 'expected': 'c'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 26,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Last Char',
  'description': 'Return last character of s.',
  'starter': 'def last_char(s):\n    pass',
  'tests': [{'input': "last_char('cat')", 'expected': 't'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 27,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'To Uppercase',
  'description': 'Convert string to uppercase.',
  'starter': 'def to_upper(s):\n    pass',
  'tests': [{'input': "to_upper('cat')", 'expected': 'CAT'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 28,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'To Lowercase',
  'description': 'Convert string to lowercase.',
  'starter': 'def to_lower(s):\n    pass',
  'tests': [{'input': "to_lower('CAT')", 'expected': 'cat'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 29,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Strip Spaces',
  'description': 'Remove leading and trailing spaces.',
  'starter': 'def strip_spaces(s):\n    pass',
  'tests': [{'input': "strip_spaces('  hi  ')", 'expected': 'hi'}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 30,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Count Occurrences',
  'description': 'Count how many times char appears in s.',
  'starter': 'def count_occ(s, char):\n    pass',
  'tests': [{'input': "count_occ('hello', 'l')", 'expected': 2}],
  'hint': 'Try writing out standard python.',
  'tags': ['strings']},
 {'id': 31,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'List Sum',
  'description': 'Return sum of all numbers in list.',
  'starter': 'def list_sum(lst):\n    pass',
  'tests': [{'input': 'list_sum([1,2,3])', 'expected': 6}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists', 'math']},
 {'id': 32,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'List Max',
  'description': 'Return largest number in list.',
  'starter': 'def list_max(lst):\n    pass',
  'tests': [{'input': 'list_max([1,5,2])', 'expected': 5}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists', 'math']},
 {'id': 33,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'List Min',
  'description': 'Return smallest number in list.',
  'starter': 'def list_min(lst):\n    pass',
  'tests': [{'input': 'list_min([1,5,2])', 'expected': 1}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists', 'math']},
 {'id': 34,
  'difficulty': 'Easy',
  'points': 100,
  'title': 'Reverse List Easy',
  'description': 'Return reversed list.',
  'starter': 'def reverse_list(lst):\n    pass',
  'tests': [{'input': 'reverse_list([1,2,3])', 'expected': [3, 2, 1]}],
  'hint': 'Try writing out standard python.',
  'tags': ['lists']},
 {'id': 35,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Remove Duplicates',
  'description': "Return list with duplicates removed, order doesn't matter.",
  'starter': 'def remove_duplicates(lst):\n    pass',
  'tests': [{'input': 'sorted(remove_duplicates([1,2,2,3]))', 'expected': [1, 2, 3]}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 36,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Factorial',
  'description': 'Return factorial of n. (n >= 0)',
  'starter': 'def factorial(n):\n    pass',
  'tests': [{'input': 'factorial(5)', 'expected': 120}],
  'hint': 'Think about edge cases.',
  'tags': ['math', 'recursion']},
 {'id': 37,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Count Vowels',
  'description': 'Count number of vowels (a,e,i,o,u) in string.',
  'starter': 'def count_vowels(s):\n    pass',
  'tests': [{'input': "count_vowels('hello')", 'expected': 2}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 38,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Is Palindrome',
  'description': 'Return True if s reads the same forward and backward.',
  'starter': 'def is_palindrome(s):\n    pass',
  'tests': [{'input': "is_palindrome('racecar')", 'expected': True}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 39,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Fibonacci',
  'description': 'Return nth Fibonacci number (0th is 0, 1st is 1)',
  'starter': 'def fibonacci(n):\n    pass',
  'tests': [{'input': 'fibonacci(5)', 'expected': 5}],
  'hint': 'Think about edge cases.',
  'tags': ['math', 'recursion']},
 {'id': 40,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Merge Two Dictionaries',
  'description': 'Merge two dictionaries, d2 overwrites d1 on conflict.',
  'starter': 'def merge_dicts(d1, d2):\n    pass',
  'tests': [{'input': "merge_dicts({'a':1}, {'b':2})", 'expected': {'a': 1, 'b': 2}}],
  'hint': 'Think about edge cases.',
  'tags': ['dicts']},
 {'id': 41,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Find Missing Number',
  'description': 'Given list of numbers from 0 to n with one missing, find it.',
  'starter': 'def missing_number(lst):\n    pass',
  'tests': [{'input': 'missing_number([0,1,3])', 'expected': 2}],
  'hint': 'Think about edge cases.',
  'tags': ['lists', 'algorithms']},
 {'id': 42,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Sum of Digits',
  'description': 'Return sum of digits of positive integer n.',
  'starter': 'def sum_digits(n):\n    pass',
  'tests': [{'input': 'sum_digits(123)', 'expected': 6}],
  'hint': 'Think about edge cases.',
  'tags': ['math']},
 {'id': 43,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Are Anagrams',
  'description': 'Return True if s1 and s2 are anagrams.',
  'starter': 'def are_anagrams(s1, s2):\n    pass',
  'tests': [{'input': "are_anagrams('listen', 'silent')", 'expected': True}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 44,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Reverse Words',
  'description': 'Reverse the order of words in string word by word.',
  'starter': 'def reverse_words(s):\n    pass',
  'tests': [{'input': "reverse_words('hello world')", 'expected': 'world hello'}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 45,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Count Words',
  'description': 'Count number of words in string separated by spaces.',
  'starter': 'def count_words(s):\n    pass',
  'tests': [{'input': "count_words('hello world')", 'expected': 2}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 46,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Most Frequent Char',
  'description': 'Return the character that appears most often.',
  'starter': 'def most_frequent(s):\n    pass',
  'tests': [{'input': "most_frequent('hello')", 'expected': 'l'}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 47,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Intersection of Lists',
  'description': 'Return common elements in both lists.',
  'starter': 'def intersection(l1, l2):\n    pass',
  'tests': [{'input': 'sorted(intersection([1,2,3], [2,3,4]))', 'expected': [2, 3]}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 48,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Difference of Lists',
  'description': 'Return elements in l1 not in l2.',
  'starter': 'def difference(l1, l2):\n    pass',
  'tests': [{'input': 'sorted(difference([1,2,3], [2,3,4]))', 'expected': [1]}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 49,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Flatten List',
  'description': 'Flatten a 2D list into a 1D list.',
  'starter': 'def flatten(lst):\n    pass',
  'tests': [{'input': 'flatten([[1,2], [3]])', 'expected': [1, 2, 3]}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 50,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Sort Dictionary by Value',
  'description': 'Return list of keys sorted by their ascending values.',
  'starter': 'def sort_dict(d):\n    pass',
  'tests': [{'input': "sort_dict({'a':3, 'b':1, 'c':2})", 'expected': ['b', 'c', 'a']}],
  'hint': 'Think about edge cases.',
  'tags': ['dicts', 'algorithms']},
 {'id': 51,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Title Case',
  'description': 'Capitalize first letter of every word.',
  'starter': 'def title_case(s):\n    pass',
  'tests': [{'input': "title_case('hello world')", 'expected': 'Hello World'}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 52,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Binary to Decimal',
  'description': 'Convert binary string to integer.',
  'starter': 'def bin_to_dec(b):\n    pass',
  'tests': [{'input': "bin_to_dec('101')", 'expected': 5}],
  'hint': 'Think about edge cases.',
  'tags': ['math']},
 {'id': 53,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'List of Primes',
  'description': 'Return list of prime numbers up to n.',
  'starter': 'def get_primes(n):\n    pass',
  'tests': [{'input': 'get_primes(10)', 'expected': [2, 3, 5, 7]}],
  'hint': 'Think about edge cases.',
  'tags': ['math']},
 {'id': 54,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'GCD',
  'description': 'Return greatest common divisor of a and b.',
  'starter': 'def gcd(a, b):\n    pass',
  'tests': [{'input': 'gcd(12, 8)', 'expected': 4}],
  'hint': 'Think about edge cases.',
  'tags': ['math']},
 {'id': 55,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'LCM',
  'description': 'Return least common multiple of a and b.',
  'starter': 'def lcm(a, b):\n    pass',
  'tests': [{'input': 'lcm(4, 6)', 'expected': 12}],
  'hint': 'Think about edge cases.',
  'tags': ['math']},
 {'id': 56,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Matrix Transpose',
  'description': 'Return transposed 2D list.',
  'starter': 'def transpose(matrix):\n    pass',
  'tests': [{'input': 'transpose([[1,2], [3,4]])', 'expected': [[1, 3], [2, 4]]}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 57,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Second Largest',
  'description': 'Find second largest number in list.',
  'starter': 'def second_largest(lst):\n    pass',
  'tests': [{'input': 'second_largest([1, 5, 3, 4])', 'expected': 4}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 58,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Remove Vowels',
  'description': 'Return string without vowels.',
  'starter': 'def remove_vowels(s):\n    pass',
  'tests': [{'input': "remove_vowels('hello')", 'expected': 'hll'}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 59,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Dict from two lists',
  'description': 'Create dict from list of keys and val.',
  'starter': 'def to_dict(keys, values):\n    pass',
  'tests': [{'input': "to_dict(['a','b'], [1,2])", 'expected': {'a': 1, 'b': 2}}],
  'hint': 'Think about edge cases.',
  'tags': ['dicts', 'lists']},
 {'id': 60,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Find Pairs',
  'description': 'Find two numbers in list that add up to target and return as a tuple (sorted). Return None if none.',
  'starter': 'def find_pairs(lst, target):\n    pass',
  'tests': [{'input': 'find_pairs([1,2,3,4], 5)', 'expected': (1, 4)}],
  'hint': 'Think about edge cases.',
  'tags': ['lists', 'algorithms']},
 {'id': 61,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Is Sorted',
  'description': 'Return True if list is sorted in ascending order.',
  'starter': 'def is_sorted(lst):\n    pass',
  'tests': [{'input': 'is_sorted([1,2,3])', 'expected': True}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 62,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Rotate List',
  'description': 'Rotate list to the right by k steps.',
  'starter': 'def rotate(lst, k):\n    pass',
  'tests': [{'input': 'rotate([1,2,3,4,5], 2)', 'expected': [4, 5, 1, 2, 3]}],
  'hint': 'Think about edge cases.',
  'tags': ['lists']},
 {'id': 63,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Check Subsequence',
  'description': 'Return True if s1 is subsequence of s2.',
  'starter': 'def is_subsequence(s1, s2):\n    pass',
  'tests': [{'input': "is_subsequence('abc', 'ahbgdc')", 'expected': True}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 64,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Capitalize Alternate Matrix',
  'description': 'Capitalize alternate letters.',
  'starter': 'def alt_caps(s):\n    pass',
  'tests': [{'input': "alt_caps('hello')", 'expected': 'HeLlO'}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 65,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Count Bits',
  'description': 'Return number of 1s in binary representation of n.',
  'starter': 'def count_bits(n):\n    pass',
  'tests': [{'input': 'count_bits(5)', 'expected': 2}],
  'hint': 'Think about edge cases.',
  'tags': ['math']},
 {'id': 66,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Is Power of Two',
  'description': 'Return True if n is power of two.',
  'starter': 'def is_power_of_two(n):\n    pass',
  'tests': [{'input': 'is_power_of_two(8)', 'expected': True}],
  'hint': 'Think about edge cases.',
  'tags': ['math']},
 {'id': 67,
  'difficulty': 'Medium',
  'points': 200,
  'title': 'Group Anagrams Medium',
  'description': 'Group anagrams together from a list of strings but just return the count of groups.',
  'starter': 'def group_anagrams_medium(strs):\n    pass',
  'tests': [{'input': "group_anagrams_medium(['eat', 'tea', 'tan'])", 'expected': 2}],
  'hint': 'Think about edge cases.',
  'tags': ['strings']},
 {'id': 68,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Longest Palindromic Substring',
  'description': 'Return the longest palindromic substring.',
  'starter': 'def longest_palindrome(s):\n    pass',
  'tests': [{'input': "longest_palindrome('babad') in ['bab', 'aba']", 'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 69,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Merge Intervals',
  'description': 'Merge overlapping intervals.',
  'starter': 'def merge_intervals(intervals):\n    pass',
  'tests': [{'input': 'merge_intervals([[1,3],[2,6],[8,10]])', 'expected': [[1, 6], [8, 10]]}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 70,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Trapping Rain Water',
  'description': 'Calculate how much water can be trapped after raining.',
  'starter': 'def trap(heights):\n    pass',
  'tests': [{'input': 'trap([0,1,0,2,1,0,1,3,2,1,2,1])', 'expected': 6}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 71,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Word Break',
  'description': 'Return True if string can be segmented into dictionary words.',
  'starter': 'def word_break(s, word_dict):\n    pass',
  'tests': [{'input': "word_break('leetcode', ['leet', 'code'])", 'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 72,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Longest Consecutive Sequence',
  'description': 'Find length of longest consecutive elements sequence.',
  'starter': 'def longest_consecutive(nums):\n    pass',
  'tests': [{'input': 'longest_consecutive([100, 4, 200, 1, 3, 2])', 'expected': 4}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 73,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Edit Distance',
  'description': 'Minimum operations to convert word1 to word2.',
  'starter': 'def edit_distance(word1, word2):\n    pass',
  'tests': [{'input': "edit_distance('horse', 'ros')", 'expected': 3}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 74,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Maximum Subarray',
  'description': 'Return max sum of contiguous subarray.',
  'starter': 'def max_subarray(nums):\n    pass',
  'tests': [{'input': 'max_subarray([-2,1,-3,4,-1,2,1,-5,4])', 'expected': 6}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 75,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Coin Change',
  'description': 'Minimum coins to make amount.',
  'starter': 'def coin_change(coins, amount):\n    pass',
  'tests': [{'input': 'coin_change([1,2,5], 11)', 'expected': 3}],
  'hint': 'Optimize for time and space.',
  'tags': ['algorithms']},
 {'id': 76,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Sudoku Validator',
  'description': 'Validate a partially filled 9x9 sudoku board. Only columns matters in this simple test.',
  'starter': 'def is_valid_sudoku(board):\n    pass',
  'tests': [{'input': "is_valid_sudoku([['5','3','.','.','7','.','.','.','.'],['6','.','.','1','9','5','.','.','.'],['.','9','8','.','.','.','.','6','.'],['8','.','.','.','6','.','.','.','3'],['4','.','.','8','.','3','.','.','1'],['7','.','.','.','2','.','.','.','6'],['.','6','.','.','.','.','2','8','.'],['.','.','.','4','1','9','.','.','5'],['.','.','.','.','8','.','.','7','9']])",
             'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 77,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Generate Parentheses',
  'description': 'Return list of all well-formed parentheses strings.',
  'starter': 'def generate_parentheses(n):\n    pass',
  'tests': [{'input': 'sorted(generate_parentheses(3))',
             'expected': ['((()))', '(()())', '(())()', '()(())', '()()()']}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms', 'recursion']},
 {'id': 78,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Permutations',
  'description': 'Return all possible permutations of list.',
  'starter': 'def permute(nums):\n    pass',
  'tests': [{'input': 'sorted(permute([1,2]))', 'expected': [[1, 2], [2, 1]]}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms', 'recursion']},
 {'id': 79,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Subsets',
  'description': 'Return all possible subsets.',
  'starter': 'def subsets(nums):\n    pass',
  'tests': [{'input': 'sorted(subsets([1,2]))', 'expected': [[], [1], [1, 2], [2]]}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 80,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Jump Game',
  'description': 'Determine if you can reach the last index.',
  'starter': 'def can_jump(nums):\n    pass',
  'tests': [{'input': 'can_jump([2,3,1,1,4])', 'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 81,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Unique Paths',
  'description': 'Find number of unique paths in m x n grid.',
  'starter': 'def unique_paths(m, n):\n    pass',
  'tests': [{'input': 'unique_paths(3, 7)', 'expected': 28}],
  'hint': 'Optimize for time and space.',
  'tags': ['algorithms']},
 {'id': 82,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Climbing Stairs',
  'description': 'Distinct ways to climb n stairs (1 or 2 steps).',
  'starter': 'def climb_stairs(n):\n    pass',
  'tests': [{'input': 'climb_stairs(3)', 'expected': 3}],
  'hint': 'Optimize for time and space.',
  'tags': ['algorithms']},
 {'id': 83,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Search in Rotated Sorted Array',
  'description': 'Return index of target in rotated sorted array, or -1.',
  'starter': 'def search(nums, target):\n    pass',
  'tests': [{'input': 'search([4,5,6,7,0,1,2], 0)', 'expected': 4}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 84,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Construct String from Tree (List representation)',
  'description': 'Simply return string representation.',
  'starter': 'def tree_to_str(lst):\n    pass',
  'tests': [{'input': 'tree_to_str([1,2,3])', 'expected': '[1, 2, 3]'}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings']},
 {'id': 85,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Find Peak Element',
  'description': 'Return index of peak element.',
  'starter': 'def find_peak(nums):\n    pass',
  'tests': [{'input': 'find_peak([1,2,3,1])', 'expected': 2}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 86,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Longest Valid Parentheses',
  'description': 'Length of longest valid parentheses substring.',
  'starter': 'def longest_valid(s):\n    pass',
  'tests': [{'input': "longest_valid(')()())')", 'expected': 4}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 87,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Minimum Path Sum',
  'description': 'Find path from top left to bottom right minimizing sum.',
  'starter': 'def min_path_sum(grid):\n    pass',
  'tests': [{'input': 'min_path_sum([[1,3,1],[1,5,1],[4,2,1]])', 'expected': 7}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 88,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Decode Ways',
  'description': 'Number of ways to decode digit string.',
  'starter': 'def num_decodings(s):\n    pass',
  'tests': [{'input': "num_decodings('226')", 'expected': 3}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 89,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Wildcard Matching',
  'description': 'Implement wildcard matching with ? and *.',
  'starter': 'def is_match(s, p):\n    pass',
  'tests': [{'input': "is_match('aa', '*')", 'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 90,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'N-Queens Count',
  'description': 'Return number of distinct solutions to N-Queens puzzle.',
  'starter': 'def total_n_queens(n):\n    pass',
  'tests': [{'input': 'total_n_queens(4)', 'expected': 2}],
  'hint': 'Optimize for time and space.',
  'tags': ['algorithms', 'recursion']},
 {'id': 91,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Maximal Rectangle',
  'description': 'Find largest rectangle of 1s in 2D binary matrix.',
  'starter': 'def maximal_rectangle(matrix):\n    pass',
  'tests': [{'input': "maximal_rectangle([['1','0','1','0','0'],['1','0','1','1','1'],['1','1','1','1','1'],['1','0','0','1','0']])",
             'expected': 6}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 92,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Interleaving String',
  'description': 'Determine if s3 is an interleaving of s1 and s2.',
  'starter': 'def is_interleave(s1, s2, s3):\n    pass',
  'tests': [{'input': "is_interleave('aabcc', 'dbbca', 'aadbbcbcac')", 'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 93,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Distinct Subsequences',
  'description': 'Number of distinct subsequences of s that equal t.',
  'starter': 'def num_distinct(s, t):\n    pass',
  'tests': [{'input': "num_distinct('rabbbit', 'rabbit')", 'expected': 3}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 94,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Word Ladder Length',
  'description': 'Shortest transformation sequence from begin to end word.',
  'starter': 'def ladder_length(begin, end, word_list):\n    pass',
  'tests': [{'input': "ladder_length('hit', 'cog', ['hot','dot','dog','lot','log','cog'])", 'expected': 5}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings', 'algorithms']},
 {'id': 95,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Kth Largest Element',
  'description': 'Find kth largest element.',
  'starter': 'def find_kth_largest(nums, k):\n    pass',
  'tests': [{'input': 'find_kth_largest([3,2,1,5,6,4], 2)', 'expected': 5}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 96,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Majority Element',
  'description': 'Find majority element.',
  'starter': 'def majority_element(nums):\n    pass',
  'tests': [{'input': 'majority_element([3,2,3])', 'expected': 3}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 97,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Search 2D Matrix',
  'description': 'Search for value in 2D sorted matrix.',
  'starter': 'def search_matrix(matrix, target):\n    pass',
  'tests': [{'input': 'search_matrix([[1,3,5,7],[10,11,16,20],[23,30,34,60]], 3)', 'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 98,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Rotate Image',
  'description': 'Rotate nxn matrix 90 degrees clockwise in-place, then return it.',
  'starter': 'def rotate_image(matrix):\n    pass',
  'tests': [{'input': 'rotate_image([[1,2,3],[4,5,6],[7,8,9]])', 'expected': [[7, 4, 1], [8, 5, 2], [9, 6, 3]]}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 99,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Group Anagrams',
  'description': 'Group anagrams together and return list of lists.',
  'starter': 'def group_anagrams(strs):\n    pass',
  'tests': [{'input': "sorted([sorted(x) for x in group_anagrams(['eat','tea','tan','ate','nat','bat'])])",
             'expected': [['ate', 'eat', 'tea'], ['bat'], ['nat', 'tan']]}],
  'hint': 'Optimize for time and space.',
  'tags': ['lists', 'algorithms']},
 {'id': 100,
  'difficulty': 'Hard',
  'points': 300,
  'title': 'Valid Anagram',
  'description': 'Return True if t is an anagram of s.',
  'starter': 'def is_anagram(s, t):\n    pass',
  'tests': [{'input': "is_anagram('anagram', 'nagaram')", 'expected': True}],
  'hint': 'Optimize for time and space.',
  'tags': ['strings']}]
